### ISSUE TITLE
Autorisatie meldingen

### ISSUE THREAD

**Issue by roymilder** [tapsterbv/issue-tracker#10]
Wanneer je de agenda opent en je klikt bovenaan op een grijs gebied, krijg je soms random een Ooops 403 melding (GET /tickets/). Dit gebeurt soms ook nadat je bug regel 15 hebt gereproduceerd. Uiteindelijk kan het zelfs resulteren in een Serverfout 500 (er is iets verkeerd gegaan). Gebeurt ook als je op een ander menu item klikt.
[[BIJLAGE R16]]

**Comment by roymilder** [comment]
#3 

autorisatie melding is niet reproduceerbaar.

**Comment by Basshoo** [comment]
Dag Tapster,

Ik krijg deze nu vaker dan verwacht. Wordt ook wat mij betreft een blocking-bug. Het is niet mogelijk om een nieuwe agenda item toe te voegen of deze te bewerken. Zie onderstaande GIF. De eerste 2 keer klik ik op een grijs veld. De 3e keer op een activiteit. 

![calendar_403](https://user-images.githubusercontent.com/95341649/144570325-cd5d822a-98af-4050-8726-3ceb7cfe49fe.gif)
.

**Comment by roymilder** [comment]
@Basshoo 
Ik heb je hier apart over gemaild, betreft een rechteninstelling. Ik heb de rechten aangepast op productie.
