### ISSUE TITLE
Kleuren bullets bij agenda in beheeromgeving

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#14]
**Beschrijf de bug**
Er zijn meerdere locaties (agenda's) toegevoegd aan de omgeving. Hierdoor hebben alle bullets een blauwe kleur.

**Reproduceren**
1. Ga naar de beheeromgeving.
2. Kies Agenda
3. Alle bullets zijn hier blauw

**Verwachting**
Meerdere kleuren bullets

**Screenshots**
![image](https://user-images.githubusercontent.com/95341649/144245290-20ac9f77-3399-4ecd-bb14-9926d5b3a3cc.png)

**Desktop (info toevoegen):**
Windows 11, laptop, Microsoft Edge

**Overige informatie**

**Comment by DaanEliens** [comment]
We hebben 8 kleuren tot onze beschikking voor de verschillende agenda's. De eerste 8 agenda's zijn inmiddels voorzien van een andere kleur. Ik zet deze verbetering door naar @roymilder om aanvullende kleuren te implementeren in de agenda.

**Comment by roymilder** [comment]
De vraag is even waar het dan ophoudt. Als ik als voorbeeld de outlook agenda bekijk dan zit daar ook een limiet op van +/- 8 kleuren. Ik zie geen bezwaar om het aantal kleuren nog iets op te hogen. Maar aangezien het uiteindelijke aantal agenda's dat je kan aanmaken arbitrair is kan er altijd een tekort aan kleuren zijn.

Ik zal het item op de ontwikkelagenda zetten met het verzoek tot uitbreiding naar 15 - 20 kleuren. We zijn daarbij wel gebonden aan de beschikbare kleuren binnen ons framework (is niet onbeperkt). Wel hebben we de mogelijkheid om verschillende tinten op te nemen. Of dat een optie is laat ik nog even in het midden.

**Comment by Basshoo** [comment]
Outlook heeft 8 kleuren, deze herhalen zich in de volgorde 1,2,3,4,5,6,7,8. Lijkt mij voor Tapster platform ook prima. Risico is dat op het moment dat je meer dan 8 filters aan hebt staan, je activiteiten van dezelfde kleur gaat zien. Ik weet niet of dit vaak/uberhaupt voorkomt.

**Comment by DaanEliens** [comment]
Aangepast.
