### ISSUE TITLE
Ctrl Reload op agenda - performance op t

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#16]
**Beschrijf de bug**
Als ik in de beheer- productieomgeving een Ctrl+R (Reload) geef op de Calendar pagina, duurt het even voordat de beheerpagina weer opent. Als ik in diezelfde sessie klik op 'activiteiten' in de frontend, heeft de omgeving het eventjes zwaar met ophalen van de activiteiten. Als de beheeromgeving is geladen, laden de activiteiten in.

**Reproduceren**
1. Log in op de beheeromgeving
2. Open het agenda tabblad
3. Ctrl R op het agenda tabblad
4. Direct daarna in frontend op 'activiteiten' klikken (laden duurt langer)
5. Beheerpagina klaar met laden? Activiteiten laden dan ook weer in.

**Verwachting**
Agenda pagina opent na een reload. Een frontend omgeving die niet langer moet laden door een Ctrl Reload (CTRL + R Windows) op de agenda pagina.

**Screenshots**
![ctrlR_reload](https://user-images.githubusercontent.com/95341649/144266106-70920f58-77ef-473e-ac8b-8e443259e49f.gif)

**Desktop (info toevoegen):**
Windows 11, Microsoft Edge

**Overige informatie**
Mogelijk onderdeel van een reeks query verbeteringen.

**Comment by Basshoo** [comment]
Mogelijk relatie met #11.
Agenda bugs pauzeer ik even tot release vrijdag a.s.

**Comment by roymilder** [comment]
Als je ditzelfde op acceptatie doet (je doet deze test op productie) dan zal je dit niet ervaren. Op productie nemen de calls die je laat zien op de frontend 6 seconden en op beheer +/- 20 seconden in beslag.

Op acceptatie nemen ze beide nog geen 400ms in beslag.

Achtergrondinformatie - jouw sessie wordt naar dezelfde server gerouteerd. Met andere woorden, als jij een zware call uitvoert dan heeft jouw volgende call daar potentieel last vast. Een andere gebruiker die op hetzelfde moment een verzoek uitvoert routeren we naar een andere server. Op deze manier zorgen we er voor dat een gebruiker bij zware calls er vooral zelf last van heeft en een andere gebruiker niet.

**Comment by Basshoo** [comment]
Ik kan dit niet meer reproduceren. Beschrijving is opgelost. Lijkt te maken te hebben gehad met #11
