### ISSUE TITLE
Wisselen tussen week lijkt afspraken te dupliceren

### ISSUE THREAD

**Issue by roymilder** [tapsterbv/issue-tracker#18]
**Beschrijf de bug**
Bij het wisselen tussen weken in de agenda lijkt bij terugkomst op een reeds bekeken week de afspraken dubbel (en driedubbel, vierdubbel et cetera) te worden weergegeven.

**Reproduceren**
Stappen om de bug te reproduceren:
1. open de agenda
2. bekijk een week met activiteiten
3. ga een week verder
4. ga een week terug
5. activiteiten staan dubbel in de agenda.

**Verwachting**
Activiteiten horen slechts eenmaal in de agenda te staan.

**Comment by roymilder** [comment]
Het wisselen tussen de weken is met het oog op #3 aangepast. Er wordt niet meer gecached. 
De bug wordt veroorzaakt doordat er op 1 plek toch nog deels data gecached wordt. Bij het wisselen tussen weken komt dit naar voren. 

Het betreft hier een weergave bug.

Voor deze bug is een intern ticket aangemaakt 
https://github.com/tapsterbv/tapster-admin/issues/61

De fix wordt 3/12 doorgevoerd naar de productie omgeving van beheer.

**Comment by roymilder** [comment]
Er is daarnaast aangegeven dat dit mogelijk ook leidt tot meerdere meldingen dat je bent ingeschreven. Dit heb ik zelf nog niet kunnen reproduceren. Er worden bij mij niet meer meldingen verstuurd dan gewenst.

Dit is na te gaan door de logging na te kijken. 

Om de zaken zuiver te houden gaan we als volgt te werk:

- Vrijgeven bug fix
- Bijwerken acceptatie
- Betreffende acceptatie omgeving van de klant bijwerken met productie dump
- Bug proberen te reproduceren. 
- Afhankelijk van constateringen aanpassingen doorvoeren.

**Comment by Basshoo** [comment]
@roymilder : de meerdere meldingen dan nodig is mijn foute constatering. Door de herhaalde afspraak tot 6 maanden, resulteert dit gewoon in een hoeveelheid meldingen naar de host van 'inschrijving'.

**Comment by roymilder** [comment]
Ja, dat zou een goede verklaring kunnen zijn. Het klopt dat dit individuele notificaties worden en geen verzamelnotificatie met daar een ical bestand met een repeterende afspraak. Omdat de activiteiten net iets anders werken dan een traditionele agenda kunnen we de ical niet inrichten zoals gebruikelijk.

Ik zeg daarbij nog niet. Op dit moment hebben we gewoon nog onvoldoende data uit de praktijk om goed in te schatten hoe een repeterende ical ingericht moet worden. Dit is dus iets wat over +/- 6 maanden weer op de ontwikkellijst naar voren komt.

Om dit dus te ondervangen hebben we de optie om de host te informeren togglebaar gemaakt. Je kan na het inplannen wel voor de losse afspraak nog een reminder sturen.
