### ISSUE TITLE
Wijzigen reeks niet mogelijk

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#19]
**Beschrijf de bug**
Een aangemaakte reeks kan niet meer worden gewijzigd, en resulteert in een fout:
"Endpoint: PUT /activities/recurring/:id". De éérste afspraak van de reeks heeft ook niet de optie "Reeks aanpassen" maar alleen "Deze activiteit". Het verwijderen van de reeks gaat alleen goed, 1 afspraak verder dan de 'originele' afspraak die als 1e is aangemaakt. Deze afspraak dient dan los verwijderd te worden.

**Reproduceren**
1. Maak een reeks aan van 'herhaal 7 dagen - eindigt op 03-06-2022'
2. Geef alle data op zoals een omschrijving, host, datum van terugkeer etc.
3. Sla het item op.

**Verwachting**
Dat de gehele reeks aangepast kan worden en de gehele reeks ook wijzigt, plus dat de 1e afspraak gewijzigd kan worden.

**Screenshots**
Screenshot begin v.d. reeks:
![image](https://user-images.githubusercontent.com/95341649/144579932-6d18426a-3d76-479d-9329-34a3a966e26d.png)

Aanpassen item verder in de reeks:
![calendar_reeks](https://user-images.githubusercontent.com/95341649/144581224-43603881-b035-4bbd-b21c-55f1dcf271e1.gif)

**Desktop (info toevoegen):**
Windows 11, Edge

* Blocking. Wijzigen reeks afspraken moet mogelijk zijn.

**Comment by roymilder** [comment]
Die betreffende actie was niet verrecht aan een beheerder:

![Screenshot 2021-12-03 at 17 06 12](https://user-images.githubusercontent.com/2341834/144634276-5e873549-d11d-4eec-bfc3-2da75e7519fc.png)

Alleen moderators & gebruikers mochten die aanpassing doorvoeren.

Inmiddels ook verrechting op aan beheerder gegeven.
