### ISSUE TITLE
Gebruikers uitnodigen mislukt

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#20]
**Beschrijf de bug**
Wanneer gebruikers uitgenodigd worden via de beheeromgeving > Gebruikers, mislukt het uitnodigen. De foutmeldig 'Er is iets verkeerd gegaan. Controleer de log' komt naar voren. Zowel bij moderators als beheerders gebeurt dit.

**Reproduceren**
1. Ga naar de beheeromgeving
2. Klik op Gebruikers
3. Klik op 'Toevoegen' rechts bovenin
4. Vul de gegevens van de deelnemer in
5. Vinkje aan bij uitnodigen
6. Foutmelding

**Verwachting**
Bevestiging van uitnodigen deelnemer

**Screenshots**
![2021-12-06 13_38_23-SHA-5CD109CVXY - ConnectWise Control - Connected](https://user-images.githubusercontent.com/95341649/144847990-baf0e62a-171c-4819-89c4-d795be3e68c3.png)

**Desktop (info toevoegen):**
Windows 11, Edge

**Comment by Basshoo** [comment]
Blocking issue

**Comment by DaanEliens** [comment]
Ik heb het gecontroleerd en kan mezelf uitnodigingen.  Mogelijk bestaat dit account al?

**Comment by Basshoo** [comment]
Nee. Dit is geverifieerd.
![image](https://user-images.githubusercontent.com/95341649/144848794-e1206bf0-1956-437a-b766-2795f2c3c96f.png)

**Comment by DaanEliens** [comment]
Ik vermoed dat dit niet de volledige naam is. Het zoeken hierop moeten we nog optimaliseren. Als je bijvoorbeeld zoekt naar Daa, dan kun je me ook niet vinden. Zoek je naar Daan, dan kun je me wel vinden. Ik bel je even om het te checken.
