### ISSUE TITLE
Foutmelding bij openen gebruikers op TIM

### ISSUE THREAD

**Issue by christyzwambach** [tapsterbv/issue-tracker#20]
# **🐞 Bug Report**

**Bij het maken van een melding mag er geen informatie zijn die te herleiden is naar een organisatie of persoon. Voor screenshots, gebruik de demo-omgeving van Digidagbesteding of Tim van Tapster.**

## **Stappen om te reproduceren**
1. Ga naar <https://demo.timvantapster.nl/beheer/gebruikers?state=Totaall>
2. Klik op ....
3. Et cetera

## **Voeg screenshots toe**
![Schermafbeelding 2024-04-03 094021](https://github.com/tapsterbv/issue-tracker/assets/165260320/85610a14-a01b-49f5-b1a9-4df94c135fb6)

**Comment by roymilder** [comment]
@christyzwambach 
https://demo.timvantapster.nl/beheer/gebruikers?state=Totaall

Deze link klopt niet, de toevoeging ?state=Totaall zorgt voor de foutmelding
Heb je dit zelf toegevoegd of ben je hier gekomen door ergens op te klikken?
