### ISSUE TITLE
Notificatie bij annulering activiteit

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#22]
**Describe the solution you'd like**
Wanneer een activiteit niet doorgaat vanwege ziekte van een host of omdat er te weinig deelnemers zijn, is een functie gewenst die ervoor zorgt dat een annulering van een activiteit kenbaar wordt gemaakt. Dit kan op 2 manieren:

1. In de agenda laten zien door vb. een streep door de activiteit te plaatsen
2. Een e-mailbericht aan alle deelnemers van één specifieke activiteit waarin staat vermeldt dat de activiteit voor datum X, activiteit X, is geannuleerd.

**Describe alternatives you've considered**
Contacteren via WhatsApp is voor alle cliënten niet altijd mogelijk.

**Comment by roymilder** [comment]
Dit bespreken we morgen om negen uur in het overleg.

Werkwijze: indien een activiteit geannuleerd wordt ontvangen deelnemers + hosts een notificatie. Exacte inhoud van de e-mail moeten we nog afstemmen.
