### ISSUE TITLE
Notificatie bij inschrijving van cliënt op activiteit

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#23]
**Describe the solution you'd like**
Wanneer een cliënt zich aanmeldt via een activiteit of wordt uitgenodigd in de activiteit via de beheeromgeving, is het wenselijk dat de host wordt geïnformeerd over de deelname. Nu moet op de dag zelf beoordeeld worden hoeveel cliënten er zijn.

**Describe alternatives you've considered**
n.v.t.

**Comment by roymilder** [comment]
8u.

**Comment by roymilder** [comment]
Dit bespreken we morgen om negen uur in het overleg. 

Werkwijze: indien een cliënt zich inschrijft op een activiteit ontvangen de hosts op deze activiteit een notificatie per e-mail. Exacte inhoud van de e-mail moeten we nog afstemmen.

**Comment by roymilder** [comment]
Tekst:
{user.displayName} is ingeschreven voor {doc.subject}

**Comment by roymilder** [comment]
Het is ook mogelijk om een notificatie te ontvangen als een cliënt zich uitschrijft:

Tekst:
{user.displayName} is uitgeschreven voor {doc.subject}
