### ISSUE TITLE
Weergave aantal ingeschreven deelnemers & maximaal aantal deelnemers

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#24]
**Is your feature request related to a problem? Please describe.**
Deze feature bestaat uit 2 onderdelen:
1. Voor bepaalde activiteiten kunnen maar een X aantal cliënten meedoen. Bij het aanmaken van een activiteit is het wenselijk dat het aantal deelnemers opgegeven kan worden wat maximaal mee kan doen aan de activiteit, totdat deze vol zit met inschrijvingen. 
2. Het is al mogelijk om te zien hoeveel deelnemers er zijn aangemeld. Dit moet dan uitgebreid worden met het aantal maximale deelnemers (zie screenshot). Vb. 0 v.d. 20 deelnemers.

![image](https://user-images.githubusercontent.com/95341649/145179536-9f94b18b-9842-41dc-a3e7-9300324e6465.png)

**Comment by roymilder** [comment]
Wordt besproken op woensdag 5/1. Bij het aanmaken kan een maximaal aantal deelnemers worden opgegeven (default = 30).
