### ISSUE TITLE
Notificatie hosts - aanmaken activiteit

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#25]
**Describe the solution you'd like**
Wanneer je als host een activiteit plant, krijg je daar e-mails van. Dit zijn echter dezelfde e-mails die cliënten ook ontvangen. Een bevestiging van deelname. Voor hosts zou het, lijkt mij, beter zijn dat je een e-mail krijgt die aangeeft dat je activiteit voor <Datum> is ingepland.* Aanvullend misschien één uur voor deelname nog een herinnering naar cliënt en/of host? Ook daarin e-mailberichten specificeren.

* voor een reeks het iCal bestand & data combineren. Daar zit meer aan vast zoals het versturen van updates etc. zoals besproken met Roy.

**Comment by roymilder** [comment]
Er is een apart event beschikbaar (uuid: 3df26ee6-0a86-4673-90af-2a532ce55d4a). Dit event gaat alleen naar de hosts. Aan dit event kan een aparte notificatie gekoppeld worden. Tekst moet afgestemd worden.

**Comment by roymilder** [comment]
Huidige tekst:

Onderwerp:
Je bent aangemeld als host op {doc.subject}

Inhoud:
Je bent aangemeld als organisator op {doc.subject}. Deze activiteit vindt plaats van {doc.start} tot {doc.end}
