### ISSUE TITLE
Vinkje Agenda 'alles (de)selecteren'

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#26]
Op het moment dat je de beheeromgeving opent (Agenda), zou het wenselijk zijn om alle agenda's te selecteren of de-selecteren.

**Comment by roymilder** [comment]
Komt beschikbaar op acceptatie 5/1.

![Screenshot 2022-01-04 at 08 39 40](https://user-images.githubusercontent.com/2341834/148025268-58b0c038-15d6-4ff6-93e6-27ad07b52654.png)
