### ISSUE TITLE
Activiteit toevoegen via "Toevoegen" knop geeft 500-fout

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#28]
**Beschrijf de bug**
Wanneer ik een activiteit wil toevoegen via de "Toevoegen" knop in de testomgeving, geeft dat bij stap 2 van het toevoegen op de achtergrond een 500-fout. Op de voorgrond ontstaat de fout 'Cannot convert undefined or null to object'

**Reproduceren**
1. Klik op Toevoegen
2. Selecteer een categorie
3. Klik op Volgende
4. Foutmelding op de voor- en achtergrond

**Verwachting**
Activiteit toevoegen.

**Screenshots**
![toevoegen-fout](https://user-images.githubusercontent.com/95341649/148945586-b0e54d64-5b1b-46e1-aeac-25fdb70378b0.gif)

**Desktop (info toevoegen):**
- Windows 10, Edge

**Comment by roymilder** [comment]
De melding wordt veroorzaakt door de afbeelding die bij de betreffende categorie is geuploaded. Het betreft hier een afbeelding die is toegevoegd aan de categorie maar die waarschijnlijk door de copy van productie naar acceptatie corrupt is.
Ik heb de betreffende afbeelding even aangepast door een recente. Daardoor werkt alles naar behoren.
