### ISSUE TITLE
Nieuwe activiteiten en agenda items niet zichtbaar

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#30]
**Beschrijf de bug**
Wanneer ik een agenda item toevoeg in de Agenda van de testomgeving, wordt deze niet zichtbaar aan de voorkant.

**Reproduceren**
1. Voeg een agenda-item toe in de backend
2. Vul de informatie in zoals activiteit soort, datum, herhalingspatroon, host, locatie en aantal deelnemers.
3. Klik op opslaan
4. Nieuw aangemaakte item niet zichtbaar.

**Verwachting**
Dat mijn activiteit én agenda item zichtbaar zouden zijn.

**Screenshots**
![image](https://user-images.githubusercontent.com/95341649/148947960-1fe8c0ee-d268-40d1-8dfe-01a6af92a898.png)
![image](https://user-images.githubusercontent.com/95341649/148948037-b34b1e47-b176-4f4d-93b4-7b8f4257f453.png)
![image](https://user-images.githubusercontent.com/95341649/148948069-acfbbab6-5334-4e78-89a7-4103c003ef15.png)
![image](https://user-images.githubusercontent.com/95341649/148948098-97de7d3b-e7b1-43a8-b889-d46c74881282.png)

**Desktop (info toevoegen):**
- Windows 10, Edge

**Comment by roymilder** [comment]
Binnen DDB kennen we een rollen en rechtensysteem. Dit rollen en rechtensysteem bepaalt wat wel en niet mag op Digidagbesteding qua tonen van content. Dit systeem heeft geen betrekking op beheer. De toegang tot beheer wordt op een andere manier geregeld. Daarbij maken we binnen beheer geen onderscheid in content. Beheer verrechten we op functies, DDB verrechten we op toegang tot content.

Jij hebt een item aangemaakt in de categorie "Eigen Regie". Deze heb je aangemaakt via Beheer.

Als je kijkt bij de inrichting dan zie je dat er verder geen verrechting aan de voorkant is op de categorie Eigen Regie. Dat klopt namelijk ook, die categorie is oorspronkelijk aangemaakt maar later is besloten om die weg te halen.

Het klopt dus dat je die items niet aan de voorkant terugziet op jouw account: je hebt er namelijk ook geen toegang toe.
![Screenshot 2022-01-12 at 09 32 16](https://user-images.githubusercontent.com/2341834/149091802-20b147eb-7e84-43ca-93e7-b95b93f23acb.png)

**Comment by roymilder** [comment]
Samen met Bas doorlopen op de test omgeving.
