### ISSUE TITLE
Locatie-tag/keuze niet altijd in profiel zichtbaar

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#31]
**Beschrijf de bug**
Wanneer ik mijn eigen profiel open, zie ik geen locaties meer staan. Soms, met een Ctrl Reload zie ik dit wel verschijnen.

**Reproduceren**
1. Klik rechts bovenin op het bolletje van je profiel
2. Locatie-tags niet zichtbaar.
3. Indien wel zichtbaar; klik op "Opslaan". Switch dan tussen een tabblad op DigiDB, daarna locaties verdwenen.

**Verwachting**
Dat deze altijd zichtbaar zijn.

**Screenshots**
![image](https://user-images.githubusercontent.com/95341649/148948352-00d52306-bc89-43dd-ba47-40a0ce011473.png)
![image](https://user-images.githubusercontent.com/95341649/148948470-a0198697-e3ef-447d-8ec2-175f67dc900d.png)

**Desktop (info toevoegen):**
- Windows 10, Edge

**Comment by roymilder** [comment]
Kan het zijn dat hij nog aan het laden is?
Ik kan dit item namelijk niet reproduceren.

In plaats van dat we hier een lader tonen is het item pas zichtbaar als alle data goed is ingeladen. Is de data nog niet beschikbaar (om welke reden dan ook) dan is het veld gewoon niet toegankelijk. 

Dit is by design.

Straks even doornemen.

**Comment by Basshoo** [comment]
Hi Roy,

Is niet aan het laden. Ik kan wel andere locaties kiezen namelijk. 
1. Klik op profiel (afbeelding rechts boven)
2. Klik op opslaan
3. Klik op menuknop Activiteiten
4. Keer terug naar profiel via afbeelding rechts boven
5. Locaties zijn weg.

Na +/- 1 minuut wachten geen locaties zichtbaar nog. Met Ctrl R wel instant weer. Kan ik laten zien.

**Comment by roymilder** [comment]
De weergave na een update en/of wisseling van tabblad was niet altijd goed. Dit probleem is verholpen. Ook na een update en/of wisseling worden de geselecteerde kenmerken goed weergegeven.
