### ISSUE TITLE
Deelnemer meermaals aan agenda toevoegen is mogelijk

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#32]
**Beschrijf de bug**
Wanneer ik een deelnemer uitnodig voor een willekeurig agenda-item, kan ik net zo vaak op inschrijven drukken als dat ik wil.

**Reproduceren**
1. Klik op een agenda item
2. Selecteer een deelnemer
3. Klik op Inschrijven (herhaal dit)

**Verwachting**
Een melding die stelt dat de deelnemer al is uitgenodigd & dan ook niet extra wordt toegevoegd.

**Screenshots**
![image](https://user-images.githubusercontent.com/95341649/148949076-7c3465bb-8efa-497c-8c9d-89938b27a4e4.png)

**Desktop (info toevoegen):**
- Windows 10, Edge

**Comment by roymilder** [comment]
<img width="693" alt="Screenshot 2022-01-14 at 10 09 49" src="https://user-images.githubusercontent.com/2341834/149489417-f0dbbbde-2f84-4cc5-830e-a9c225b0ada8.png">
