### ISSUE TITLE
Toevoegen gebruikers overschrijven, ondanks melding 'in gebruik'

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#33]
**Beschrijf de bug**
Wanneer ik een Gebruiker/deelnemer toevoeg met hetzelfde e-mailadres, ontstaat er een melding dat het e-mailadres al in gebruik is. Desondanks kan ik dan wel op "Toevoegen" klikken. 

**Reproduceren**
1. Kopieer een e-mailadres van een willekeurige gebruiker
2. Klik op Toevoegen
3. Negeer de melding dat het e-mailadres in gebruik is
4. Klik op toevoegen (gebruiker komt er dan ook 2x in te staan in het overzicht tot een refresh)
5. Refresh de pagina
6. Gebruiker overschreven

**Verwachting**
Niet kunnen toevoegen van de gebruiker omdat het e-mailadres al bestaat.

**Screenshots**
![image](https://user-images.githubusercontent.com/95341649/148949565-efabd070-2447-4e81-97b6-f7da62e506ea.png)
![image](https://user-images.githubusercontent.com/95341649/148949682-ccb36698-7da0-4c8a-bb63-7da8f08cd4e0.png)
![image](https://user-images.githubusercontent.com/95341649/148949759-b249956d-e1fe-432c-806b-6cb413d386b0.png)
Na een refresh & toevoegen:
![image](https://user-images.githubusercontent.com/95341649/148949849-b849e03c-5f41-4099-98d4-bc8867fd6bb0.png)

**Desktop (info toevoegen):**
- Windows 10, Edge

**Comment by roymilder** [comment]
![Screenshot 2022-01-12 at 12 03 39](https://user-images.githubusercontent.com/2341834/149128508-a477a2d0-5b41-41bc-8dd7-0e590f3379a0.png)

Het lijkt er op dat de validatie op de knop uit was gezet. Bij een ongeldig formulier moet de status van de knop ook ongeldig zijn.,
