### ISSUE TITLE
Wijzigen profielfoto in productie mislukt

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#34]
**Beschrijf de bug**
Gebruikers kunnen hun profielfoto niet meer wijzigen in productie (ik, maar ook collega e.k - v.d.b). Dit resulteert in een "Er gaat iets verkeerd." melding.

**Reproduceren**
1. Klik op je profielfoto rechts bovenin
2. Klik op "Wijzigen"
3. Selecteer een (nieuwe) profielfoto.
4. Foutmelding

**Verwachting**
Wijzigen van profielfoto zou goed moeten gaan.

**Screenshots**
![profielfoto](https://user-images.githubusercontent.com/95341649/148950997-97efb796-7c2f-4149-b1d3-8b6ea6f8bf1e.gif)

**Desktop (info toevoegen):**
 - Windows 10, Edge

**Comment by roymilder** [comment]
Betreft een bug die al is opgelost. Staat al live op de acceptatie omgeving en op de productie omgevingen die dagelijks worden bijgewerkt.
