### ISSUE TITLE
Beheermodule laadt niet door

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#37]
**Beschrijf de bug**
Wanneer ik in productie naar de beheeromgeving wil, blijft de beheermodule laden. Hier klaren meerdere collega's over. Dit probleem is gister gemeld aan Daan door p.k.

**Reproduceren**
1. Log in op productie
2. Klik op beheer
3. Beheer laadt niet door

**Verwachting**
De beheermodule

**Screenshots**
![image](https://user-images.githubusercontent.com/95341649/149473100-749ea07e-fd17-4ae2-b88a-4750e933de52.png)

**Desktop (info toevoegen):**
 - Windows 10, Edge

**Overige informatie**
Alle informatie die voor ons relevant kan zijn om de bug te verhelpen.

**Comment by roymilder** [comment]
probleem is gisteren verholpen. 
er was een corrupt media bestand op een cdn terechtgekomen. bij het inladen van beheer wordt de tijdlijn van activiteiten ingeladen. één van deze activiteiten bevatte een verwijzing naar dit corrupte bestand.

Probleem is gisteren verholpen door de tijdlijn tijdelijk uit te zetten. Hierdoor kon beheer weer doorladen.

Deze ochtend is de tijdlijn tijdelijk weer geactiveerd om het exacte bestand te achterhalen. Daarna is de tijdlijn weer gedeactiveerd. Inmiddels is er een fix beschikbaar die einde dag wordt vrijgegeven. Deze fix zorgt er voor dat ook activiteiten met in corrupt bestand door kunnen laden. Mocht er in de toekomst toch een corrupt bestand voorkomen dan zorgt dit niet meer voor problemen.
