### ISSUE TITLE
Aanmelden voor activiteit testomgeving mislukt

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#41]
**Beschrijf de bug**
Wanneer ik aan een activiteit op de testomgeving wil deelnemen, ontstaat er een fout.
1. Foutje...
2. Cast to ObjectId failed for value "blanco-notification" (type string) at path "_id" for model "MessageTemplate

**Reproduceren**
1. Klik op een Agenda Item
2. Klik op de knop 'Klik hier om deel te nemen'
3. Fout.
4. (Na refresh fout weg, melding: de activiteit is nog niet begonnen. Fout lijkt dan gedeeltelijk weg behalve foutmelding nr 1).

**Verwachting**
Aanmelding die lukt.

**Screenshots**
![image](https://user-images.githubusercontent.com/95341649/154037089-3eba4234-a93e-480e-a4de-fe74e94caef9.png)
![image](https://user-images.githubusercontent.com/95341649/154037129-1ad3d599-60cb-49b9-9c19-3ae121f11b45.png)

**Desktop (info toevoegen):**
Windows 10, Edge

**Comment by roymilder** [comment]
opgelost.
