### ISSUE TITLE
Annuleren activiteit geeft fout

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#42]
**Beschrijf de bug**
Wanneer in de beheermodule een activiteit wordt geannuleerd, komt er een JSON-foutmelding naar voren. De activiteit is wel geannuleerd. Onduidelijk is hoe dit precies is ontstaan.

**Verwachting**
Geen foutmelding

**Screenshots**
![image](https://user-images.githubusercontent.com/95341649/157458833-bf5c802f-3caa-4201-9e3e-469e870b7fc2.png)

**Desktop (info toevoegen):**
 - Edge, W10

**Overige informatie**
Collega M.H. - Intern: I2203 461

**Comment by Basshoo** [comment]
Intern: I2203 1475
Zie onderstaande beschrijving. Soortgelijke foutmelding.

Ik heb vanochtend de activiteit van MO Hardenberg aangepast voor de datums 13,14, 20, 21 april, omdat de host die het normaal doet (I. G.) met vakantie is, en haar collega D.W. het overneemt op deze datums.
Nu zie ik in de agenda dat ze activiteiten er dubbel in staan (twee keer breinjoggen, twee keer fit en vitaal). Dit komt vermoedelijk omdat ik de host heb veranderd.
Ik heb ook de tijd van de activiteiten moeten veranderen, vanwege de zomertijd klopte het tijdstip niet meer van de activiteit.
Wanneer ik de dubbele activiteit eruit wil halen, krijg ik een foutmelding (zie onderstaande)

Kunnen jullie dit misschien oplossen? De juiste tijd is: 9:30-11:45 en 9:30-11:00. Op bovenstaande data met host D.W, de andere data met host I. G.

![image](https://user-images.githubusercontent.com/95341649/161254583-77c37158-e05c-45ad-a977-db34b3f99f18.png)

**Comment by roymilder** [comment]
Dit is opgelost op zowel acceptatie als productie.
