### ISSUE TITLE
Filtering in Gebruikerbeheer

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#43]
**Beschrijf de bug**
Wanneer ik in Gebruikersbeheer zoek naar de eerste paar letters van een medewerker, vb: "Eve", dan krijg ik geen resultaten. Ik moet een volledige voornaamstring ingeven voordat het resultaat naar voren komt.

**Reproduceren**
Stappen om de bug te reproduceren:
1. Ga naar gebruikers
2. Zoek 'Eve'
3. Geen resultaat
4. Vul volledige naam in, wel resultaat.

**Verwachting**
Alle namen die 'eve' bevatten.

**Comment by roymilder** [comment]
Op dit moment zoeken we alleen op volledige namen. Het is momenteel niet mogelijk om op delen van namen te zoeken. Dit heeft te maken met de wijze waarop we indexeren.

Dit staat aan onze kant niet al bug maar als uitbreiding functionaliteit.
