### ISSUE TITLE
Verwijderen user geeft foutmelding

### ISSUE THREAD

**Issue by Basshoo** [tapsterbv/issue-tracker#44]
**Beschrijf de bug**
Wanneer ik een gebruiker verwijder in gebruikersbeheer, krijg ik eerst een witte popup. Daarna is deze popup gevuld met een foutmelding dat er iets is verkeerd gegaan.

**Reproduceren**
Stappen om de bug te reproduceren:
1. Ga naar gebruikersbeheer
2. Zoek een gebruiker
3. Klik gebruiker aan
4. Klik op 3 potloodje
5. Klik onderaan op 'Verwijderen'

Dit was bij een inactieve gebruiker (standaardrol). Niet getest voor andere soorten.

**Verwachting**
Wat had je verwacht dat er zou gebeuren?
Geen foutmelding

**Screenshots**
Indien mogelijk, stuur screenshots m
![nr2](https://user-images.githubusercontent.com/95341649/158830888-b503c9f1-4890-44de-9467-31b1fcae6f7d.png)
ee.

**Comment by roymilder** [comment]
Deze functionaliteit was tot op heden alleen voorbehouden aan medewerkers van Tapster. Functionaliteit is nu verduidelijkt.

Er wordt onderscheid gemaakt tussen twee statussen:
- Verwijderd
- Geanonimiseerd

Verwijderd:
Een account dat wordt verwijderd wordt ook daadwerkelijk uit het systeem gehaald. Er blijft geen enkele verwijzing meer over. Gerelateerde gebruikersdata (iedere regel waar een verwijzing zit naar dit account) wordt ook verwijderd. Concreet betekent dit dat gebruikersdata, historie en logging hierdoor ook aangepast wordt

Geanonimiseerd:
Een account dat de status geanonimiseerd heeft blijft gewoon bestaan binnen Tapster. Gebruikersdata, logging en historie blijven ook bestaan. Dit heeft dus geen impact op rapportages. Persoonsgegevens worden geanonimiseerd. Er zijn dus geen herleidbare persoonsgegevens meer binnen Tapster. Met deze optie bewaar je dus wel historie maar voldoe je aan de AVG.

Een account wordt in twee stappen geanonimiseerd. Eerst krijgt het de status 'Te anonimiseren'. Binnen 24u wordt het account dan ook daadwerkelijk geanonimiseerd (in de praktijk om 01.00u 's nachts).

Een account dat verwijderd wordt wordt **direct** verwijdert. Dit kan niet ongedaan gemaakt worden.
