### ISSUE TITLE
Foutmelding

### ISSUE THREAD

**Issue by CasperTapster** [tapsterbv/issue-tracker#49]
# **🐞 Bug Report**

**Bij het maken van een melding mag er geen informatie zijn die te herleiden is naar een organisatie of persoon. Voor screenshots, gebruik de demo-omgeving van Digidagbesteding of Tim van Tapster.**

## **Omschrijf het probleem**
Klant kreeg foutmelding bij het plaatsen van een artikel. Nadat ik het account nogmaals op actief had gezet, verdween de foutmelding. 
Maar wat was er nu echt aan de hand? 

## **Stappen om te reproduceren**
1. Ga naar <url>Lentis. Gebruiker Tineke Weerts
2. Klik op ....
3. Et cetera

## **Voeg screenshots toe**
![image](https://github.com/tapsterbv/issue-tracker/assets/165002167/a325ab14-3ed4-4221-98ef-06f25490114c)

Met Windows een screenshot maken:
Gebruik de toetsencombinatie: Windows + Shift + s.
Hierna kan je het gebied selecteren wat je gescreenshot wilt hebben.

**Comment by roymilder** [comment]
opgelost
