### ISSUE TITLE
Verzendschema

### ISSUE THREAD

**Issue by CasperTapster** [tapsterbv/issue-tracker#54]
# **🐞 Bug Report**

**Bij het maken van een melding mag er geen informatie zijn die te herleiden is naar een organisatie of persoon. Voor screenshots, gebruik de demo-omgeving van Digidagbesteding of Tim van Tapster.**

## **Omschrijf het probleem**
Voorheen konden we het verzendschema van de nieuwsbrieven aanpassen. Deze functie is verdwenen. Kan deze week terugkomen? 

## **Stappen om te reproduceren**
1. Ga naar <url>
2. Klik op ....
3. Et cetera

## **Voeg screenshots toe**
Met Windows een screenshot maken:
Gebruik de toetsencombinatie: Windows + Shift + s.
Hierna kan je het gebied selecteren wat je gescreenshot wilt hebben.

**Comment by CasperTapster** [comment]
Wanneer deze functie terugkomt; is het mogelijk om de weekenddagen uit te sluiten? Door de week hebben we de mogelijkheid de berichten aan te passen.

**Comment by roymilder** [comment]
Deze staat er weer.
is het mogelijk om de weekenddagen uit te sluiten?
Ja, dit kan al, speciale aandacht voor de maandag in onderstaand screenshot (3 dagen ipv 1)
<img width="801" alt="Screenshot 2024-07-08 at 13 19 44" src="https://github.com/tapsterbv/issue-tracker/assets/2341834/adfeae0f-01bb-4b20-aab0-f799ddedf44b">
