### ISSUE TITLE
Geen teksten in de beheer-module

### ISSUE THREAD

**Issue by CasperTapster** [tapsterbv/issue-tracker#6]
# **🐞 Bug Report**

**Bij het maken van een melding mag er geen informatie zijn die te herleiden is naar een organisatie of persoon. Voor screenshots, gebruik de demo-omgeving van Digidagbesteding of Tim van Tapster.**

## **Omschrijf het probleem**
Geen teksten in de beheer-module. Dit is bij alle klanten

## **Stappen om te reproduceren**
1. Ga naar <url> https://www.timvantapster.nl/beheer/dashboard

## **Voeg screenshots toe**
![image](https://github.com/tapsterbv/issue-tracker/assets/165002167/57566257-d5ab-4968-8a69-48a01b9edf91)

**Comment by roymilder** [comment]
Dit is geen bug: in verband met bepaalde resoluties/ benodigde ruimte zijn de labels weggehaald.
