### ISSUE TITLE
Geen e-mail ontvangen als host

### ISSUE THREAD

**Issue by roymilder** [tapsterbv/issue-tracker#6]
**Beschrijf de bug**
Geen mail gekregen als Host van kahoot quiz Steenwijk? (hoe kan dit)

**Comment by roymilder** [comment]
Vanwege het terugkerend inplannen en verwijderen van activiteiten is de optie om de host te informeren instelbaar geworden. Dit omdat het anders tot gevolg kan hebben dat bij een terugkerende afspraak er erg veel notificaties verstuurd worden. Dit heeft weer samenhang met de hosts die af kunnen wijken binnen een terugkerende afspraak.

![Screenshot 2021-12-01 at 06 43 13](https://user-images.githubusercontent.com/2341834/144178505-471ef68e-94c2-499a-98f4-bebd3dadc8f6.png)

In bovenstaand screenshot is de toggle te zien. Deze toggle is beschikbaar op acceptatie.

**Comment by Basshoo** [comment]
Dag Roy,

Wat betreft de toggle:

Wat gebeurt er als je nu een terugkerende afspraak inplant. Is de toggle dan ook beschikbaar en krijg je dan alsnog een X aantal notificaties of kan dit enkel per losse activiteit verstuurd worden. Misschien deze ook opnemen in de documentatie?
