### ISSUE TITLE
Huisstijl testomgeving

### ISSUE THREAD

**Issue by roymilder** [tapsterbv/issue-tracker#8]
**Beschrijf de bug**
Daan gaf aan dat de huisstijl was verwerkt in de testomgeving. Deze zie ik echter nergens terug. Kan de doorgevoerde huisstijl nader gespecificeerd worden? Waar is dit gepubliceerd?

**Comment by DaanEliens** [comment]
Dit heeft betrekking op de standaard afbeeldingen bij de categorieën. Deze zijn op zowel productie als acceptatie verwerkt.
